@contact_id = 
### Create Contact
POST http://localhost:8080/api/v1/contacts HTTP/1
Content-Type: application/json

{
    "name": "Irving",
    "phone": "1234567890"
}

### Get Contact
GET  http://localhost:8080/api/v1/contacts/{{contact_id}} HTTP/1

### Update Contact
PUT http://localhost:8080/api/v1/contacts/{{contact_id}} HTTP/1
Content-Type: application/json

{
    "name": "Irving",
    "phone": "123456789"
}

### Delete Contact
DELETE  http://localhost:8080/api/v1/contacts/{{contact_id}} HTTP/1